### ISSUE TITLE
Kargoya verildi maili?

### ISSUE THREAD

**Issue by rifatozkancomtr** [unbelievable-digital/kargo-takip-turkiye#1]
Merhabalar eklenti için teşekkürler ürün kargoya verildik den sonra mail göndermiyor ekleme şansınız varmı kargoya verildi maili ve takip linki gibi?

**Comment by ZgrK** [comment]
Sürüm 0.1.0 kadar ekleyeceğim bu özelliği bakalım :)

**Comment by ZgrK** [comment]
En son yayınladığımız sürümle bu özelliklendi.  

https://github.com/unbelievable-digital/kargo-takip-turkiye/releases/tag/0.0.7
