### ISSUE TITLE
Woocommerce Takip No yönlendirmesi

### ISSUE THREAD

**Issue by isaphlivan** [unbelievable-digital/kargo-takip-turkiye#10]
woocommerce siparişlerim ekranında kargo firmaların üzerine gelince sipariş sayfasına girmeden kargo takip kodu görüntülenmesi veya yönlendirmesi yapılabilir.

**Comment by ZgrK** [comment]
Bu yapıldı şuandaki git sürümü böyle 0.2.0 sürümümzüde wordpress.org a da gelecek
