### ISSUE TITLE
Sendeo Kargo Eklenmesi

### ISSUE THREAD

**Issue by ZgrK** [unbelievable-digital/kargo-takip-turkiye#4]
Kargo firmalarinin arasina Sendeo Kargo eklenmesi gerekiyor https://wordpress.org/support/topic/sendeo-kargo-2/ istek yapilmis

**Comment by ZgrK** [comment]
c05b99e2d915d850b0eed2356b52e3bff5706979 bu commit'te ekledim

**Comment by ocuonline** [comment]
Sendeo Kargo firmasını kapatıyorum ama yenilediğimde hala açık halde geliyor.

**Comment by ZgrK** [comment]
Yeni bir verison peşindeyim bu sorunlcaır cozeceğız
